# Generated by Django 3.2.15 on 2024-09-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('idea_id', models.IntegerField(primary_key=True, serialize=False)),
                ('submitted_date_time', models.DateTimeField()),
                ('idea_status', models.CharField(max_length=100)),
                ('creator_id', models.CharField(max_length=100)),
                ('creator_department', models.CharField(max_length=100)),
                ('times_shared', models.IntegerField()),
                ('votes', models.IntegerField()),
                ('comments', models.IntegerField()),
                ('views', models.IntegerField()),
                ('keywords', models.TextField(blank=True)),
            ],
        ),
    ]
